if(!exists("mat.bc")){
  source("StartPreprocessData.R")
  source("filterBrainColonData.R")
  source("DendogramBrain.R")
  source("DendogramColon.R")
  source("quantileNormalization.R")
  source("Regression.R")
  #source("Correlation.R")
  #source("mlModels.R")
}
